version: '3.8'
services:
  client-frontend:
   image: geoweb-frontend:0.0.1
   container_name: geoweb_client
   build:
    context: .
    dockerfile: ./docker/frontend/Dockerfile
   restart: always
   ports:
     - '3000:3000'
  nginx: 
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 81:80
  client-backend:
    container_name: geoweb_api
    image: geoweb-backend:0.0.1
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    depends_on:
      - service-db
    environment:
      SERVER_PORT: ${API_INTERNAL_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRY_MINUTES: ${JWT_ACCESS_EXPIRY_MINUTES}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRY_DAYS: ${JWT_REFRESH_EXPIRY_DAYS}
  service-db:
    container_name: ${POSTGRES_HOST}
    image: 'postgis/postgis:latest'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - D:\docker-volumes\geoweb\postgres:/var/lib/postgresql/data
    restart: unless-stopped
  minio:
    container_name: ${MINIO_HOST}
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - D:\docker-volumes\geoweb\minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    #external: true  