version: '3.8'
services:
  client-frontend:
   image: geoweb-frontend:0.0.1
   container_name: geoweb_client
   build:
    context: .
    dockerfile: ./docker/frontend/Dockerfile
   restart: always
   ports:
     - '3000:3000'
  nginx: 
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 81:80
  client-backend:
    container_name: geoweb_api
    image: geoweb-backend:0.0.1
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    volumes:
      - geoserver_icons:${APP_GEOSERVER_ICONS_PATH}
    depends_on:
      - db
      - minio
      - geoserver
    environment:
      SERVER_PORT: ${API_INTERNAL_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRY_MINUTES: ${JWT_ACCESS_EXPIRY_MINUTES}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRY_DAYS: ${JWT_REFRESH_EXPIRY_DAYS}
      GEOSERVER_URL: http://${GEOSERVER_HOST}:8080/geoserver/
      GEOSERVER_WORKSPACE: ${GEOSERVER_WORKSPACE}
      GEOSERVER_DATASTORE: ${GEOSERVER_DATASTORE}
      APP_MINIO_HOST: http://${MINIO_HOST}
      APP_MINIO_PORT: ${MINIO_PORT}
      APP_MINIO_USER: ${MINIO_ROOT_USER}
      APP_MINIO_PASSWORD: ${MINIO_ROOT_PASSWORD}
      APP_GEOSERVER_ICONS_PATH: ${APP_GEOSERVER_ICONS_PATH}
      GEOSERVER_DATA_DIR: ${GEOSERVER_DATA_DIR}
      GEOSERVER_ICONS_PATH: ${GEOSERVER_ICONS_PATH}
  db:
    container_name: ${POSTGRES_HOST}
    image: 'postgis/postgis:latest'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./docker-data/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: geoweb_pgadmin4
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5151:80"
    volumes:
      - ./docker-data/pgadmin-data:/var/lib/pgadmin
  minio:
    container_name: ${MINIO_HOST}
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
  geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      container_name: geoweb_geoserver
      volumes:
        - ./docker-data/geoserver-data:/opt/geoserver/data_dir
        - geoserver_icons:${GEOSERVER_DATA_DIR}${GEOSERVER_ICONS_PATH}
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
      depends_on:
        - db
networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    #external: true
volumes:
  geoserver_icons: