version: '3.8'
services:
  #client-frontend:
  #  image: frontend:0.0.1
  #  build: ./frontend
  #  restart: always
  #  ports:
  #    - '3000:3000'
  #  volumes:
  #    - /app/node_modules
  #    - ./frontend:/app

  client-backend:
    container_name: ${API_HOST}
    image: client-backend:0.0.1
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    depends_on:
      - service-db
    environment:
      SERVER_PORT: ${API_INTERNAL_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_INTERNAL_PORT}/{POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  service-db:
    container_name: ${POSTGRES_HOST}
    image: 'postgis/postgis:latest'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5151:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  minio:
    container_name: ${MINIO_HOST}
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
  db-data:
  pgadmin-data:

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    #external: true  